name: classic_carousel_silder
description: Ù‘Classic carousel image slider for flutter apps
version: 0.0.1
homepage: https://github.com/TahaAhvazi/classic_carousel_silder
environment:
  sdk: '>=2.19.1 <3.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0


flutter:

